name: Create Bundle

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Environment setup
        uses: ./.github/actions/setup
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          ib_user: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          ib_password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}

      - name: Create Bundle
        run: uds create --confirm
